### ISSUE TITLE
Won't load in macOS Mojave

### ISSUE THREAD

**Issue by jbenton** [adrianh/safari-count-tabs-extension#1]
I don't know if this is something you want to bother with, but macOS Mojave disallows Safari extensions from any source other than the Mac App Store, annoyingly enough. Do you anticipate putting this there?

<img width="532" alt="screen shot 2018-08-10 at 12 35 58 pm" src="https://user-images.githubusercontent.com/2439459/43971462-23500afc-9c9f-11e8-91d5-1655eded697f.png">

**Comment by adrianh** [comment]
Well… that's annoying :-)

Maybe leaning yes, but it probably won't happen until after Mojave is out of beta.

(aka I've not looked into what's needed to do that — and I probably won't have any reason to look until it stops working for me since this is a shallow solve-my-problem thing for me ATM :-)

**Comment by gingerbeardman** [comment]
Any chance of having this before Catalina?

I find this supremely useful.

**Comment by gingerbeardman** [comment]
I'd be happy to help with this. It's the only extension preventing me upgrading to Safari 13.

**Comment by adrianh** [comment]
If you have the time to poke at it feel free! However from my brief look it's gonna need a complete re-write as a Swift/Objective C extension in the new separate-app style. From a quick browse of the docs I'm not even sure that having notifications in the toolbar are even possible.

It's still on my to do list, but very low priority since it will involve me learning Swift — which will need some time on my part :)

**Comment by gingerbeardman** [comment]
Here's a modern alternative: https://github.com/otzbergnet/tabCount

Please feel free to contribute! 

And thanks for your original extension.

**Comment by gingerbeardman** [comment]
https://apps.apple.com/de/app/tab-count/id1487406555?mt=12

New extension released on Mac App Store, works in 10.13, 10.14 and 10.15 and requires no permissions to do its work. Enjoy!

**Comment by jbenton** [comment]
Awesome, thanks for your work on it!

**Comment by adrianh** [comment]
Thanks - added links to the new extension to the README for this repo :)
